[global]
   workgroup = WORKGROUP
   server string = Docker Samba Server
   log file = /var/log/samba/log.%m
   max log size = 1000
   security = user
   map to guest = never
   load printers = no
   disable spoolss = yes

[storage]
   comment = Docker Storage Share
   path = /storage
   browseable = yes
   read only = no
   guest ok = no
   valid users = ${SAMBA_USER}